### ISSUE TITLE
Feature : Add Something

### ISSUE THREAD

**Issue by Zyro231-2** [Zyro231-2/Human_mg#1]
Add anything You want.

**Comment by Sourav-Kumar-Panda** [comment]
Hey can i work on this?

**Comment by kartikaeyy** [comment]
I want to contribute. How do I start?

**Comment by DevanshYadav07** [comment]
good evening sir , where is your code so i can start contributing .

**Comment by Zyro231-2** [comment]
ill upload today at approx 8 pm there some sort of issue with my internet last night sorry for inturupt.

**Comment by AnshulGoyal589** [comment]
@Sagar01223 I would like to make contribution in this under hactoberfest 2023, kindly assign it to me

**Comment by Zyro231-2** [comment]
hey @AnshulGoyal589 You can now start working now
