### ISSUE TITLE
bug: In some cases copy button is close to the border of parent box 

### ISSUE THREAD

**Issue by Zyro231-2** [Zyro231-2/Human_mg#14]
Problem : 
Copy Button is to close to the bottom of box border 

Solution:
Make the button align to center.

<img width="299" alt="image" src="https://github.com/Zyro231-2/Human_mg/assets/75005434/042edb59-994e-4789-b4f3-5d27d4892698">

**Comment by Aditya-132** [comment]
can you assign it to me i will solve it

**Comment by Zyro231-2** [comment]
@Aditya-132  Yes Go on.

**Comment by dipenpatel1901** [comment]
If Aditya is not able to complete. Can you assign it to me?

**Comment by SAGARSINGH-1** [comment]
Work direct if you make PR and it solves the issue I merge yours.

**Comment by Zyro231-2** [comment]
Please work directly i merge your PR if it solves the issue.
