### ISSUE TITLE
feat: Create a Search bar in the Replace of "Top Courses"

### ISSUE THREAD

**Issue by Zyro231-2** [Zyro231-2/Human_mg#16]
[] Make a search box.
[] Make a profile icon.
[] Make some navigation links.

**Comment by shaheedhudheen** [comment]
Hey, i would like to work on it

**Comment by Atulsoam562003** [comment]
Hello, I can work on this. You can assign it to me Thank you.

**Comment by Sankalp20Tiwari** [comment]
I would like to work on this issue . I will be highly obiliged if you assign it to me.

**Comment by Zyro231-2** [comment]
hey @shaheedhudheen go on.

**Comment by Zyro231-2** [comment]
hey @Sankalp20Tiwari and @Atulsoam562003 if You want to work on this issue go on if I like anyone UI I merge those PR.

**Comment by AnshulGoyal589** [comment]
@Zyro231-2 i would like to contribute in this, please assign this to me.
Also I have prior experience of these projects

**Comment by Zyro231-2** [comment]
Anyone make Correct and Fast PR will get merged.

**Comment by TheShiveshNetwork** [comment]
If this issue is open, assign to me.

**Comment by Zyro231-2** [comment]
@TheShiveshNetwork assigned to you.

**Comment by TheShiveshNetwork** [comment]
@Zyro231-2 checkout PR #59
