### ISSUE TITLE
Responsive layout for cards

### ISSUE THREAD

**Issue by wongprom** [Zyro231-2/Human_mg#19]
**Is your feature request related to a problem? Please describe.**
layout for cards is not responsive between screen sizes.

**Describe the solution you'd like**
- Create 1 column design on the smallest screen.
- Create 2, 3 column design on bigger screens based on Tailwind default Breakpoints

**Additional context**
If needed, minimum styling for card component

**Screenshots**
Have cards in 1 column
_Before_
![Skärmavbild 2023-10-03 kl  10 50 21](https://github.com/Zyro231-2/Human_mg/assets/32749038/88efadea-3b58-4d64-b070-f0571e0de628)

**Success criteria**
- [ ] Responsive design for card layout

**Comment by wongprom** [comment]
Hello @Zyro231-2. If you think this issue I created is acceptable, can you please assign it to me?

This is my first @Hacktoberfest, and I appreciate this project you have created. It is big/small enough so it is not overwhelming.

**Comment by Zyro231-2** [comment]
@wongprom Go on.

**Comment by wongprom** [comment]
Thanks @Zyro231-2

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by wongprom** [comment]
Hi @Kedarnath-Rothe! My plan is to work on this issue and do a PR later tomorrow (8/10 - 2023) .

**Comment by wongprom** [comment]
Seems like Kedarnath-Rothe already made those changes...
