### ISSUE TITLE
Create the website footer and useful information

### ISSUE THREAD

**Issue by shrutsureja** [Zyro231-2/Human_mg#20]
**Is your feature request related to a problem? Please describe.**
Footer at the end of the page

**Describe the solution you'd like**
a footer will look great at the end of the page which will include 

- add a hacktober fest logo and direct link to the page
- github repo link 
- contact of the maintainers 

**Success Criteria** 
- [x] #21
- [x] #22

@Zyro231-2 
If the issue i created is good enough to solve can you please assign it to me, i would love to solve that as i'm participating in hactober fest 2023

**Comment by ishan-nahid** [comment]
!assign

**Comment by ishan-nahid** [comment]
check and marge.

**Comment by shrutsureja** [comment]
@Zyro231-2 
Sorry for the delayed work with the footer, i will submit the Footer PR by end of tomorrow for sure, If already done by someone then i'll add some extra features.

**Comment by shrutsureja** [comment]
As i the footer is added i am closing this issue now
