### ISSUE TITLE
implementing all the above features

### ISSUE THREAD

**Issue by Zyro231-2** [Zyro231-2/Human_mg#21]

**Comment by praptisharma28** [comment]
Hey @Zyro231-2 , please assign me this. I am happy to contribute.

**Comment by kunal-511** [comment]
Hey @Zyro231-2 , please assign me this. I am happy to contribute.

**Comment by Zyro231-2** [comment]
@kunal-511  and @praptisharma28  go on who is make fast and correct PR will get merged.

**Comment by shrutsureja** [comment]
@Zyro231-2 Footer has been added so you can close this issue for now
