### ISSUE TITLE
Bug: Loader is not visible when the data is fetching 

### ISSUE THREAD

**Issue by Zyro231-2** [Zyro231-2/Human_mg#3]
when press to refresh the loading text shown but the loader is not visible 

<img width="958" alt="image" src="https://github.com/Sagar01223/Human_mg/assets/75005434/e1ba43a8-62a4-4104-b76e-73bda3d42fee">

**Comment by RitikKochar0509** [comment]
I assigned myself this task and start working on this

**Comment by Zyro231-2** [comment]
@RitikKochar0509 start working

**Comment by RitikKochar0509** [comment]
I have raise one pr, can u please review it merge the pr

https://github.com/Zyro231-2/Human_mg/pull/6
