### ISSUE TITLE
navbar can be made fixed

### ISSUE THREAD

**Issue by itsgeekhokage** [Zyro231-2/Human_mg#45]
navbar travels with the page which makes it difficult to navigate, if you are downwards in the website, i think we should make the navbar fixed, @Zyro231-2 can you pls assign me this

**Comment by itsgeekhokage** [comment]
@Zyro231-2 please assign me this

**Comment by Zyro231-2** [comment]
hey @Shivam36998 assign to you

**Comment by itsgeekhokage** [comment]
Thanks, but after cloning with latest sync, this issue is already fixed, i am currently seeking to add a scroll to top button

**Comment by Zyro231-2** [comment]
Thanks, @Shivam36998 let me know it has already added.
