### ISSUE TITLE
feature: Add a logo to the main website related to website

### ISSUE THREAD

**Issue by Zyro231-2** [Zyro231-2/Human_mg#5]
Give some of the logo here

**Comment by ToobaJamal** [comment]
I would like to work on this, please

**Comment by Zyro231-2** [comment]
@ToobaJamal yes please suggest me some good logo's

**Comment by RitikKochar0509** [comment]
can i  assigned myself this issue

**Comment by Zyro231-2** [comment]
@RitikKochar0509 could You list some of logo here

**Comment by RitikKochar0509** [comment]
sure i am searching give me some time

**Comment by RitikKochar0509** [comment]
<img width="1512" alt="Screenshot 2023-10-02 at 11 42 03 PM" src="https://github.com/Zyro231-2/Human_mg/assets/69748064/3ab17ab1-00c0-4644-aa66-16d55c6baf83">

can i add this logo

**Comment by Zyro231-2** [comment]
Can you provide bunch of in a same comment

**Comment by RitikKochar0509** [comment]
<img width="1512" alt="Screenshot 2023-10-02 at 11 47 33 PM" src="https://github.com/Zyro231-2/Human_mg/assets/69748064/6bf9fcae-0957-4545-9bc4-74ab035f9909">

**Comment by RitikKochar0509** [comment]
<img width="1512" alt="Screenshot 2023-10-02 at 11 48 11 PM" src="https://github.com/Zyro231-2/Human_mg/assets/69748064/1ab51074-ec3d-40e6-a6ee-ad6c83305966">

**Comment by RitikKochar0509** [comment]
can u select any one from this list and then i will add that logo

**Comment by RitikKochar0509** [comment]
Iu want more this is the website url you can generate and tell me that logo
https://www.logoai.com/make

**Comment by Zyro231-2** [comment]
I loved the first one of this image : https://github.com/Zyro231-2/Human_mg/issues/5#issuecomment-1743518166

make a pull request for it

**Comment by RitikKochar0509** [comment]
sure

**Comment by RitikKochar0509** [comment]
and where u want u put logo on top left or top right or with titile??

**Comment by Zyro231-2** [comment]
with tittle

**Comment by RitikKochar0509** [comment]
<img width="1512" alt="Screenshot 2023-10-03 at 12 48 51 AM" src="https://github.com/Zyro231-2/Human_mg/assets/69748064/0f5ceb1f-9a4d-4607-a7b5-f9ccd995017e">

**Comment by RitikKochar0509** [comment]
It look like this is it okay

**Comment by Zyro231-2** [comment]
no i mean here :

<img width="182" alt="image" src="https://github.com/Zyro231-2/Human_mg/assets/75005434/3bd2cda2-308f-4956-88a9-124a30a68447">

**Comment by RitikKochar0509** [comment]
i don't understand can u elaborate ?

**Comment by Zyro231-2** [comment]
i mean in html head tag its an favicon

**Comment by RitikKochar0509** [comment]
ok so you want me to add this fav icon as a logo

**Comment by RitikKochar0509** [comment]
okk got it you want me to replace favicon with that icon

**Comment by RitikKochar0509** [comment]
sorry for misunderstanding..

**Comment by Zyro231-2** [comment]
Yes replace it. and make sure tag this issue

**Comment by RitikKochar0509** [comment]
done
