### ISSUE TITLE
To  become part of hactoberfest repo must have CONTRIBUTE.md file -{suggestion}

### ISSUE THREAD

**Issue by pra9patil** [Zyro231-2/Human_mg#52]
Hey @Zyro231-2  sir
Your repo and project is amazing but according to the hactoberfest guideline to evaluate the contributor under hactoberfest , repo must have CONTRIBUTE.md file so please add it ,
Friendly Suggetion .

Thank You

**Comment by Zyro231-2** [comment]
Hey @pra9patil Thank you for your suggestion and I noted Your suggestion I'll surely work on it.
