### ISSUE TITLE
Add hover effects to the navbar

### ISSUE THREAD

**Issue by harshsbhandari** [Zyro231-2/Human_mg#56]
Add some hover effects on the navbar, @Zyro231-2 pls assign this issue to me
![Screenshot (147)](https://github.com/Zyro231-2/Human_mg/assets/73375087/a6727346-05fa-419a-acb5-522ecb23d7f2)

**Comment by Zyro231-2** [comment]
try to create new navbar in replace of "Top courses"

**Comment by aks057** [comment]
can you assign me @Zyro231-2 ?
