### ISSUE TITLE
Need help for a similar project configration

### ISSUE THREAD

**Issue by shrutsureja** [Zyro231-2/Human_mg#60]
I am also making a personal project in Vite + React + tailwindcss like this one. Vite + React is done directly will creating vite but i have issues with configuration of tailwindcss. 

I have followed some online blogs but still have some issues, if you have any resources or can help me with that it would a great help.

followed this [blog](https://blog.logrocket.com/setting-up-dev-environment-react-vite-tailwind/)
![image](https://github.com/Zyro231-2/Human_mg/assets/92169549/56c7e931-55d9-4965-a624-a809789fa47c)

Sorry, i had to create a issue for this because i did not find any other social @Zyro231-2.

Thank you.

**Comment by Zyro231-2** [comment]
Hey @shrutsureja, Contact me here: https://t.me/+RHUXY6M18FIzMTQ1
its a group of some web developer.
