### ISSUE TITLE
Copy Description Button Move out of the Card

### ISSUE THREAD

**Issue by RitikKochar0509** [Zyro231-2/Human_mg#7]
In Home Page All Courses Card have Copy Description Button It is moving out of the Card ,

Ideal Behaviour is it placed inside the card and placed centre of the card

<img width="1512" alt="Screenshot 2023-10-02 at 9 26 29 PM" src="https://github.com/Zyro231-2/Human_mg/assets/69748064/b390b660-3d9e-4938-9c4b-f9c777f49e1f">

**Comment by RitikKochar0509** [comment]
I am working on this assigned my this issue can u add a label hackoctoberfest for this i am unable to add this

**Comment by Zyro231-2** [comment]
@RitikKochar0509  make sure add an image referencing to that issue

**Comment by RitikKochar0509** [comment]
Sure
