### ISSUE TITLE
Bug: Navlink is not active which is displaying 

### ISSUE THREAD

**Issue by Zyro231-2** [Zyro231-2/Human_mg#8]
Navlink "All" should be active by default

![image](https://github.com/Zyro231-2/Human_mg/assets/75005434/10bb4488-e0cd-4c4c-a179-f033a2385ab8)

**Comment by RitikKochar0509** [comment]
Start Working on this

**Comment by RitikKochar0509** [comment]
Fixed..

**Comment by Zyro231-2** [comment]
if you create a PR just tag the issue number like this : '#222'

**Comment by RitikKochar0509** [comment]
Sure Next time i will take care of this.
 Thanks
